### ISSUE TITLE
Some questions about EfficientTeacher

### ISSUE THREAD

**Issue by Lllllp93** [AlibabaResearch/efficientteacher#10]
Hello感谢作者们的工作，将半监督算法结合了广泛应用的YoloV5并得到了很大的提升，看了论文之后（还没来得及跑代码==)有几个问题想要了解一下：

1. Table 1中，我们看到本文提出的Dense Detector相比YoloV5、V7而言在参数量不相上下、计算量甚至更高的情况下的mAP仍有下降，那么为什么不考虑直接基于以上更强性能的Yolo detectors应用本文方法？
![image](https://user-images.githubusercontent.com/39562096/222347919-11544111-68b5-45da-ae2a-0d62fd3a3a04.png)

2. 目前半监督方法在one stage&anchor-free里的还主要是基于FCOS这种比较早期的detector，论文里一般没有提供基于比较sota的如YoloX等模型的效果。不知道你们有尝试将Efficient Teacher应用在yolox这类算法上吗？看起来PLA&EA也都适合anchor-free

3. 在burn-in阶段利用ublabel data进行域迁移学习的想法非常漂亮，但在消融实验里好像没单独看到DA带来的影响，不知道这一步带来的提升怎么样？Figure5中普通Burn-In效果也能达到不错，请问这里的普通burn-in是没有进行DA和adaptive threshold的吗？

**Comment by Lllllp93** [comment]
> 
> 1. 我们提出Dense Detector的主要背景是，在我们做这项工作的时候，主流的研究任务都在关注FCOS和FasterRCNN，YOLOv5这样工程化比较复杂而且代码调试复杂的工作对一般研究者来说有点‘脏’，所以我们首先需要回答一个问题，YOLOv5这个检测器到底做了哪些工作让其在工业界受到欢迎，于是我们设计了Dense Detector这个实验，用来回答多正样本和mosaic数据增强对于one stage anchor based检测器的意义。然后，我们确实也基于YOLOv7检测器进行了半监督实验，效果比我们报告的YOLOv5还要好。
> 2. 我们也将Efficient Teacher应用在包括YOLOX/v6/v8上了，都有提升，效果也会好于YOLOv5的这个版本，您的理解是对的，PLA和EA的方案和anchor based与否无关，但是学术界在anchor free的半监督上有很多很有意思的新工作出来，我们感觉需要有一个更加稳健的方案，因为您可以看到大家在实际应用半监督的时候还需要很多超参调试成本，这与我们的价值主张是违背的，所以就没有把这一块的工作放上来。
> 
了解了，我感觉半监督学习的指标除了mAP大小之外相较于原detector监督结果的提升也是非常重要的指标，从实验的结果来看EfficientTeacher带来的提升相对其他方法没有那么高（不考虑最后一行基于yoloV5的），所以如果有一版基于FCOS的可能更能跟一些SOTA方法比。
![image](https://user-images.githubusercontent.com/39562096/222374843-8afa7117-ab5a-41b6-8ef7-fb1789c6db6a.png)
不过，看起来好像随着base detector的性能提升，半监督带来的提升也变得有限，DenseTeacher在10%COCO情况下只能给PPYOLOE带来2个点左右的提升==

> 3. 域自适应那块的消融我们没放，因为在当时写论文的时候，我们发现这一部分的loss虽然对COCO任务有提升，但是我们这种学术上的“过度设计”有可能会给实际应用带来副作用，所以现在的默认实验，这个选项也是关闭的，我们最近也有在尝试一些更generalized的方案来提升全局feature和单阶段目标feature的一致性，在经过仔细论证后我们会报告这一块的进展。
> 
我本人也是希望能把半监督落地项目里完成数据闭环真的带来提升，所以你说的”DA的副作用“本来是我接下来想问的问题。以你的经验看来，实际项目中unlabel data与label data的分布差异对半监督学习的影响怎么样？（想来实际项目中unlabel data分布不会很理想）

**Comment by BowieHsu** [comment]
unlabeled data的分布会对半监督训练造成巨大的影响，我们现在有对解决这个问题有一些思路，还需要一些比较严格的对照实验来证明我们的想法。当前这个算法库是我们能提供的最接近实际生产环境的原型，希望对您有所帮助。

**Comment by Lllllp93** [comment]
好的，期待你们接下来的工作
