### ISSUE TITLE
修改yolov5模型后，用半监督的方式训练，再转换成yolov5模型后，一张图片出现了成百上千的检测框

### ISSUE THREAD

**Issue by Huoxu69** [AlibabaResearch/efficientteacher#106]
修改模型后，用yolov5的源代码和半监督的代码进行模型转换都没有问题，但是从半监督转换回去，模型预测会出现许多的异常检测框，不知道大家有没有遇到类似的问题？

**Comment by Huoxu69** [comment]
已经解决，权重赋值错误

**Comment by Meoooww** [comment]
> 已经解决，权重赋值错误

请问可以分享以下具体的做法吗？

**Comment by Huoxu69** [comment]
> > 已经解决，权重赋值错误
> 
> 请问可以分享以下具体的做法吗？

map.txt和map_v5.txt以及yolov5原框架模型要对应起来
