### ISSUE TITLE
如何切换yolo版本？

### ISSUE THREAD

**Issue by kikucxj** [AlibabaResearch/efficientteacher#12]
请问是否支持其它版本的yolo，configs/ssod中只有关于v5的配置，可否切换至V7版本进行半监督学习？

**Comment by BowieHsu** [comment]
of course，just modify the backbone and neck from ‘YOLOv5’ to ‘YOLOv7’ in the yaml，and start SSOD training。

**Comment by BowieHsu** [comment]
by the way，channel numbers also need to be modified，there is YOLOv7 yaml example under config folder.

**Comment by wmjlincy** [comment]
你好，请问yolov7的map.txt和map_v7.txt怎么生成的呢，我根据yolov7的网络结构自己生成的map.txt，转换成模型可识别的权重文件后，训练时可以跑通，但是AP0.5要比用yolov7模型跑的结果小10%左右。可以麻烦提供下yolov7对应的map.txt和map_yolov7文件吗?

**Comment by delicate00** [comment]
> 你好，请问yolov7的map.txt和map_v7.txt怎么生成的呢，我根据yolov7的网络结构自己生成的map.txt，转换成模型可识别的权重文件后，训练时可以跑通，但是AP0.5要比用yolov7模型跑的结果小10%左右。可以麻烦提供下yolov7对应的map.txt和map_yolov7文件吗?

你好，我使用v7的时候，设置了预训练权重，但是模型训练很慢。观察训练时的各项数据，我感觉是加载预训练权重的时候没能加载成功。用的博主的efficient-yolov7是这样，我自己从官网上转的ET模型也是这样。

**Comment by wmjlincy** [comment]
你好，我转换的map-v7.txt报错没跑通，后来先监督训练，再半监督训练后，效果也没有yolov7的好，应该差个两三个点吧

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年09月24日 16:44 |
| 收件人 | AlibabaResearch/efficientteacher ***@***.***> |
| 抄送人 | wmjlincy ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [AlibabaResearch/efficientteacher] 如何切换yolo版本？ (Issue #12) |

你好，请问yolov7的map.txt和map_v7.txt怎么生成的呢，我根据yolov7的网络结构自己生成的map.txt，转换成模型可识别的权重文件后，训练时可以跑通，但是AP0.5要比用yolov7模型跑的结果小10%左右。可以麻烦提供下yolov7对应的map.txt和map_yolov7文件吗?

你好，我使用v7的时候，设置了预训练权重，但是模型训练很慢。观察训练时的各项数据，我感觉是加载预训练权重的时候没能加载成功。用的博主的efficient-yolov7是这样，我自己从官网上转的ET模型也是这样。

**Comment by hecheng000** [comment]
> 你好，我转换的map-v7.txt报错没跑通，后来先监督训练，再半监督训练后，效果也没有yolov7的好，应该差个两三个点吧
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2023年09月24日 16:44 | | 收件人 | AlibabaResearch/efficientteacher ***@***.***> | | 抄送人 | wmjlincy ***@***.***>, Comment ***@***.***> | | 主题 | Re: [AlibabaResearch/efficientteacher] 如何切换yolo版本？ (Issue #12) | 你好，请问yolov7的map.txt和map_v7.txt怎么生成的呢，我根据yolov7的网络结构自己生成的map.txt，转换成模型可识别的权重文件后，训练时可以跑通，但是AP0.5要比用yolov7模型跑的结果小10%左右。可以麻烦提供下yolov7对应的map.txt和map_yolov7文件吗? 你好，我使用v7的时候，设置了预训练权重，但是模型训练很慢。观察训练时的各项数据，我感觉是加载预训练权重的时候没能加载成功。用的博主的efficient-yolov7是这样，我自己从官网上转的ET模型也是这样。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

你好 可以分享下跑通的v7版本吗 可有偿
