### ISSUE TITLE
加载全监督训练模型进行半监督训练，检测精度低

### ISSUE THREAD

**Issue by ZHIZIHUABU** [AlibabaResearch/efficientteacher#135]
使用自己的数据集进行训练，
1、使用训练好的监督模型进行半监督训练时，map越来越低，且最好的结果仍低于初始的监督模型；
2、按照示例直接进行半监督训练时，配置文件中不加载预训练模型，P,R,Map始终为0；（示例中默认的半监督训练方案是先训220epoch的有监督，然后进入半监督），似乎并没有进行全监督训练；
3、按照示例进行全监督训练时，配置文件中不加载预训练模型，P,R,Map始终为0。

**Comment by Liumomo30** [comment]
请问您解决精度低的问题了吗，感谢回复

**Comment by eebowen** [comment]
请问解决了吗？
