### ISSUE TITLE
训练lables/P/R都为0

### ISSUE THREAD

**Issue by xiangyuli-bio** [AlibabaResearch/efficientteacher#155]

**Comment by xiangyuli-bio** [comment]
我仅修改了：yolov5l_custom_ssod.yaml的数据集路径 但是我训练的时候这些参数都为0
![image](https://github.com/user-attachments/assets/248a066e-539c-4e7b-aeb0-80fcae5e450d)

**Comment by eebowen** [comment]
请问解决了吗？我也有一样的问题

**Comment by xiangyuli-bio** [comment]
> 请问解决了吗？我也有一样的问题

我发现问题了 是因为预测框和实际框的IOU太低了 我打印看了一下 只有0.0几，我是直接按照前epoch全监督训练 后面半监督训练的 但是效果非常差，我没有深究下去了
