### ISSUE TITLE
get_label.sh 下载不了

### ISSUE THREAD

**Issue by jo-dean** [AlibabaResearch/efficientteacher#28]
`Downloading https://github.com/BowieHsu/EfficientTeacher/releases/tag/data_list/data_list.zip  ...
 -#O#-  #   #                                                                 
[data_list.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
note:  data_list.zip may be a plain executable, not an archive
unzip:  cannot find zipfile directory in one of data_list.zip or
        data_list.zip.zip, and cannot find data_list.zip.ZIP, period.`
您好，好像没有这个文件。

**Comment by BowieHsu** [comment]
您好，如果报错的话请您试试： wget https://github.com/BowieHsu/EfficientTeacher/releases/tag/data_list/data_list.zip，我这边测试是可以下载的呢

**Comment by jo-dean** [comment]
您好，还是不行
![image](https://user-images.githubusercontent.com/38728358/224959178-31dcbbf4-4668-4299-a2ca-eb6682db3c24.png)

![image](https://user-images.githubusercontent.com/38728358/224958946-ab05f00f-e20e-4340-97a1-460da2960188.png)

上面这个链接点进去
![image](https://user-images.githubusercontent.com/38728358/224959369-1100e751-8fcc-4c54-a683-bfbd8fdaa1c0.png)

**Comment by BowieHsu** [comment]
了解了，我把几个txt文件单独传上去，可能要花点时间。

**Comment by jo-dean** [comment]
明白了，我直接点击这个是正常下载的😄
![image](https://user-images.githubusercontent.com/38728358/224964862-9599b7eb-c7cc-4384-97db-f4d55322b894.png)

非常感谢。

**Comment by Haru-zt** [comment]
hi, i met the same problem,and solved it by downloading it directly . it seems that url command download a zip file which cann't unzip?

**Comment by TahereSaidi** [comment]
.
