### ISSUE TITLE
use custom dataset, new issue

### ISSUE THREAD

**Issue by Jinping-Z** [AlibabaResearch/efficientteacher#34]
你好，我遇到以下问题，你能帮我看看吗

train: __immutable__=False, __deprecated_keys__=set(), __renamed_keys__={}, __new_allowed__=False
EfficientTeacher  2023-3-15 torch 1.7.1 CUDA:0 (NVIDIA GeForce RTX 2080, 7974.0625MB)

Weights & Biases: run 'pip install wandb' to automatically track and visualize EfficientTeacher runs (RECOMMENDED)
TensorBoard: Start with 'tensorboard --logdir yolov5_ssod', view at http://localhost:6006/
Model summary: 478 layers, 47539674 parameters, 47539674 gradients

Scaled weight_decay = 0.0005
optimizer: SGD with parameter groups 110 weight, 101 weight (no decay), 104 bias
Traceback (most recent call last):
  File "train.py", line 84, in <module>
    main(opt)
  File "train.py", line 72, in main
    trainer = SSODTrainer(cfg, device, callbacks, LOCAL_RANK, RANK, WORLD_SIZE)
  File "/home/jinping/code/efficientteacher-main/trainer/ssod_trainer.py", line 60, in __init__
    self.build_dataloader(cfg, callbacks)
  File "/home/jinping/code/efficientteacher-main/trainer/ssod_trainer.py", line 225, in build_dataloader
    workers=cfg.Dataset.workers, prefix=colorstr('train: '), cfg=cfg)
  File "/home/jinping/code/efficientteacher-main/utils/datasets.py", line 334, in create_dataloader
    prefix=prefix)
  File "/home/jinping/code/efficientteacher-main/utils/datasets.py", line 704, in __init__
    if self.img_files[0].endswith('.txt') and len(self.img_files[0].split(' ')) == 2:
IndexError: list index out of range
(open-mmlab) jinping@jinping-Precision-5820-Tower:~/code/efficientteacher-main$

**Comment by BowieHsu** [comment]
@Jinping-Z 您好，看来是读训练数据的时候跑飞了，能检查一下您的train.txt里面的内容吗

**Comment by Jinping-Z** [comment]
谢谢您，根据您的建议我检查了训练集的内容，是转换过程中归一化出现了问题，.txt文件不符合要求没有归一化。

**Comment by jaideep11061982** [comment]
@Jinping-Z 
 
were you able to replicate the results on custom data set.
I am truly confused for steps to follow for Custom Data set which is mentioned.
It am not clear which Pretrained weights of YoloL to be used, trained on partial custom data set whose unlabelled images to be labelled or Pretrained on Coco dataset that we should take
1)
--what kind of supervised training is below step referring to ?
Supervised Training(Optional)
modify the train: data/custom_train.txt in yolov5l_custom.yaml, and then enter the following script.
export CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7"
python -m torch.distributed.launch --nproc_per_node 8 --master_addr 127.0.0.2 --master_port 29502 train.py --cfg configs/sup/custom/yolov5l_custom.yaml

--What are the weights to be given as pretrained weights in this step ?
SSOD Training
export CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7"
python -m torch.distributed.launch --nproc_per_node 8 --master_addr 127.0.0.2 --master_port 29502 train.py --cfg configs/sup/custom/yolov5l_custom.yaml

Also What do they mean by direct start of SSOD training
"Start SSOD Training derectly"

How do we check if our unlabelled data is labelled properly or not ,using which weights ?
