### ISSUE TITLE
关于无标签的图片问题

### ISSUE THREAD

**Issue by greedy-hat** [AlibabaResearch/efficientteacher#67]
![image](https://user-images.githubusercontent.com/46677820/231750258-0ce6cbeb-64ae-4a8e-94bb-4a5bb2f46c03.png)

**Comment by greedy-hat** [comment]
已解决

**Comment by jaideep11061982** [comment]
@greedy-hat  
were  you able to replicate the results on custom data set.
I am truly confused for steps to follow for Custom Data set which is mentioned.
It am not clear which Pretrained weights of YoloL to be used, trained on partial custom data set whose unlabelled images to be labelled or Pretrained on Coco dataset that we should take
1) 
--what kind of supervised training is below step referring to ?
Supervised Training(Optional)
modify the train: data/custom_train.txt in yolov5l_custom.yaml, and then enter the following script.
export CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7"
python -m torch.distributed.launch --nproc_per_node 8 --master_addr 127.0.0.2 --master_port 29502 train.py --cfg configs/sup/custom/yolov5l_custom.yaml

2) --What are the weights to be given as pretrained weights in this step ?
SSOD Training
export CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7"
python -m torch.distributed.launch --nproc_per_node 8 --master_addr 127.0.0.2 --master_port 29502 train.py --cfg configs/sup/custom/yolov5l_custom.yaml 

3) Also What do they mean by direct start of SSOD training
"Start SSOD Training derectly"

4) How do we check if our unlabelled data is labelled properly or not ,using which weights ?

**Comment by greedy-hat** [comment]
关于第一个问题，作者是多卡训练所需要的配置，自己可以自行修改；第二个问题，它的预训练权重是定义在它的yaml文件中，第三个问题不太清楚

**Comment by Adonis-Lbc** [comment]
> 已解决

请问您是如何解决的？

**Comment by YunFy26** [comment]
请问您是如何解决的？

**Comment by YunFy26** [comment]
> > 已解决
> 
> 请问您是如何解决的？

请问您解决了吗
