### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by David-19940718** [AlibabaResearch/efficientteacher#7]
将上面生成的unlabel.txt的绝对路径用来替换yolov5_custom.yaml的target: data_custom_target.txt，然后粘贴以下部分配置文件到yolov5l_custom.yaml中:

您好，上面这个是 README 里面的介绍，这里的 target: data_custom_target.txt 字段请问是添加在哪里？我再 yolov5l_custom.yaml 文件中并未找到。

另外我这个 custom_train.txt 是否需要涵盖 unlabel.txt 的内容，还是按照原来的监督学习默认的就行？

**Comment by BowieHsu** [comment]
@David-19940718 您好，在test下面添上target就可以了，像这样
<img width="342" alt="截屏2023-03-01 下午4 42 36" src="https://user-images.githubusercontent.com/4092342/222088094-d4df1112-4a86-4261-9225-818f253e2ebf.png">
custom_train.txt就是您原来的训练集，每一张图都需要标签，而data_custom_target.txt是没有标签的图片。
这样是为了做到有监督和半监督训练可以随时切换。

**Comment by David-19940718** [comment]
我看了下代码，你们这个好像重构过一遍了，但是README文档并没有同步，可以更新下吗？
半监督训练应该是参考 /configs/ssod/custom/yolov5l_custom_ssod.yaml 这个yaml配置，不是yolov5_custom.yaml这个。另外这个--cfg 参数应该是 --config，类似还有一些没对应。

**Comment by David-19940718** [comment]
> 

谢谢

**Comment by BowieHsu** [comment]
好的，感谢您的反馈，我来修一下

**Comment by BowieHsu** [comment]
@David-19940718 或者您修改能够运行的版本也可以提一个PR，我来合进主线。
